<?php

namespace App\Services\Registers;

use App\Models\MeetingMinutes;
use App\Models\User;
use App\Services\MeetingVisibility;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * Art. 98's register 5 — سجل المحاضر.
 *
 * Carries Stage 36's whole lifecycle (draft → pending_signatures → approved)
 * rather than only the approved ones, because Appendix 8's own gate is about
 * what happens *before* a محضر is referred for approval — a register that only
 * listed finished minutes could not show a draft that has been sitting unsigned.
 */
class MinutesRegister extends Register
{
    public function code(): string
    {
        return 'minutes';
    }

    public function nameAr(): string
    {
        return 'سجل المحاضر';
    }

    public function nameEn(): string
    {
        return 'Minutes Register';
    }

    public function columns(): array
    {
        return [
            'minutes_number' => ['ar' => 'رقم المحضر', 'en' => 'Minutes no.'],
            'meeting_number' => ['ar' => 'رقم الاجتماع', 'en' => 'Meeting no.'],
            'meeting_date' => ['ar' => 'تاريخ الاجتماع', 'en' => 'Meeting date'],
            'committee' => ['ar' => 'اللجنة', 'en' => 'Committee'],
            'status' => ['ar' => 'الحالة', 'en' => 'Status'],
            'generated_at' => ['ar' => 'تاريخ الإعداد', 'en' => 'Generated'],
            'generated_by' => ['ar' => 'أعده', 'en' => 'Generated by'],
            'reviewed_at' => ['ar' => 'تاريخ المراجعة', 'en' => 'Reviewed'],
            'reviewed_by' => ['ar' => 'راجعه', 'en' => 'Reviewed by'],
            'approved_at' => ['ar' => 'تاريخ الاعتماد', 'en' => 'Approved'],
            'signatures' => ['ar' => 'التوقيعات', 'en' => 'Signatures'],
        ];
    }

    protected function dateColumn(): string
    {
        return 'meeting_minutes.generated_at';
    }

    protected function searchColumns(): array
    {
        return ['meeting_minutes.minutes_number'];
    }

    protected function baseQuery(): Builder
    {
        return MeetingMinutes::query()
            ->with([
                'meeting:id,meeting_number,scheduled_at,committee_id',
                'meeting.committee:id,name_ar,name_en',
                'generatedBy:id,name',
                'reviewedBy:id,name',
            ])
            ->withCount([
                'signatures',
                'signatures as signed_count' => fn (Builder $query) => $query->whereNotNull('signed_at'),
            ]);
    }

    protected function row(Model $model, string $locale): array
    {
        return [
            'minutes_number' => $model->minutes_number,
            'meeting_number' => $model->meeting?->meeting_number,
            'meeting_date' => $this->date($model->meeting?->scheduled_at),
            'committee' => $this->localName($model->meeting?->committee, $locale),
            'status' => $model->status,
            'generated_at' => $this->date($model->generated_at),
            'generated_by' => $model->generatedBy?->name,
            'reviewed_at' => $this->date($model->reviewed_at),
            'reviewed_by' => $model->reviewedBy?->name,
            'approved_at' => $this->date($model->approved_at),
            'signatures' => $model->signed_count.'/'.$model->signatures_count,
        ];
    }

    /**
     * Membership gate — see Register::scopeToActor().
     *
     * @param  Builder<Model>  $query
     * @return Builder<Model>
     */
    protected function scopeToActor(Builder $query, User $actor): Builder
    {
        return $query->whereHas('meeting', fn (Builder $m) => app(MeetingVisibility::class)->apply($m, $actor));
    }
}
